INSERT INTO EMPLOYEE (id, DEPARTMENT, EMPLOYEE_NAME, EMPLOYEE_SALARY) VALUES (1, 'HR', 'Employee 1', 1000);
INSERT INTO EMPLOYEE (id, DEPARTMENT, EMPLOYEE_NAME, EMPLOYEE_SALARY) VALUES (2, 'Development', 'Employee 2', 2000);
INSERT INTO EMPLOYEE (id, DEPARTMENT, EMPLOYEE_NAME, EMPLOYEE_SALARY) VALUES (3, 'Development', 'Employee 3', 3000);
INSERT INTO EMPLOYEE (id, DEPARTMENT, EMPLOYEE_NAME, EMPLOYEE_SALARY) VALUES (4, 'HR', 'Employee 4', 4000);
INSERT INTO EMPLOYEE (id, DEPARTMENT, EMPLOYEE_NAME, EMPLOYEE_SALARY) VALUES (5, 'Sales', 'Employee 5', 5000);